### ISSUE TITLE
Error when Starting on Server 1.12.2

### ISSUE THREAD

**Issue by Live2deazh** [bspkrs/bspkrsCore#43]
My forge server won't start with version 8.0.1
I got it running with version 7.6.0.1

Even so here the crash log to fix this.

---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 2020-05-11 19:18:30 CEST
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from bspkrsCore (bspkrscore)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
    at bspkrs.util.CommonUtils.getMinecraftDir(CommonUtils.java:534)
    at bspkrs.util.CommonUtils.getConfigDir(CommonUtils.java:540)
    at bspkrs.util.UniqueNameListGenerator.run(UniqueNameListGenerator.java:27)
    at bspkrs.bspkrscore.fml.bspkrsCoreMod.postInit(bspkrsCoreMod.java:138)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
    at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:219)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 4.4.26-nitradoV3-MC-1000-nH-dP-d-i
  Java Version: 1.8.0_171, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 752576448 bytes (717 MB) / 3512205312 bytes (3349 MB) up to 6681526272 bytes (6372 MB)
  JVM Flags: 2 total; -Xms256M -Xmx7168M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 116 mods loaded, 116 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                      | Version                  | Source                                          | Signature                                |
       |:----- |:----------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
       | LCHIJ | minecraft               | 1.12.2                   | minecraft.jar                                   | None                                     |
       | LCHIJ | mcp                     | 9.42                     | minecraft.jar                                   | None                                     |
       | LCHIJ | FML                     | 8.0.99.99                | minecraft_server.jar                            | None                                     |
       | LCHIJ | forge                   | 14.23.5.2847             | minecraft_server.jar                            | None                                     |
       | LCHIJ | ivtoolkit               | 1.3.3-1.12               | minecraft.jar                                   | None                                     |
       | LCHIJ | smoothfontcore          | mc1.12.2-2.1.2           | minecraft.jar                                   | None                                     |
       | LCHIJ | xaerominimap_core       | 1.12.2-1.0               | minecraft.jar                                   | None                                     |
       | LCHIE | bspkrscore              | 8.0.0                    | [1.12.2]bspkrscore-universal-8.0.1.jar          | None                                     |
       | LCHI  | treecapitator           | 1.43.0                   | [1.12]TreeCapitator-client-1.43.0.jar           | None                                     |
       | LCHI  | buildcraftlib           | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                    | None                                     |
       | LCHI  | buildcraftcore          | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                    | None                                     |
       | LCHI  | buildcraftfactory       | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                    | None                                     |
       | LCHI  | buildcrafttransport     | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                    | None                                     |
       | LCHI  | buildcraftsilicon       | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                    | None                                     |
       | LCHI  | additionalpipes         | 6.0.0.8                  | additionalpipes-6.0.0.8.jar                     | None                                     |
       | LCHI  | applecore               | 3.2.0                    | AppleCore-mc1.12.2-3.2.0.jar                    | None                                     |
       | LCHI  | appliedenergistics2     | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar            | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | LCHI  | aroma1997core           | 2.0.0.2                  | Aroma1997Core-1.12.2-2.0.0.2.jar                | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | LCHI  | aroma1997sdimension     | 2.0.0.2                  | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.jar | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | LCHI  | autoplant               | 1.12-1.0.0               | autoplant-1.12-1.0.0.jar                        | None                                     |
       | LCHI  | backpack                | 3.0.2                    | backpack-3.0.2-1.12.2.jar                       | None                                     |
       | LCHI  | bno                     | 1.12.2-1.0.4.0           | BasicNetherOres-1.12.2-1.0.4.0.jar              | None                                     |
       | LCHI  | battletowers            | 1.6.5                    | BattleTowers-1.12.2_1.6.5.jar                   | None                                     |
       | LCHI  | baubles                 | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
       | LCHI  | bdlib                   | 1.14.3.12                | BdLib-1.12.2.jar                                | None                                     |
       | LCHI  | bibliocraft             | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar               | None                                     |
       | LCHI  | biomesoplenty           | 7.0.1.2444               | Biomes-O-Plenty-Mod-1.12.2.jar                  | None                                     |
       | LCHI  | blockcraftery           | 1.12.2-1.3.1             | blockcraftery-1.12.2-1.3.1.jar                  | None                                     |
       | LCHI  | bookshelf               | 2.3.585                  | Bookshelf-1.12.2-2.3.585.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHI  | jei                     | 4.15.0.291               | jei_1.12.2-4.15.0.291.jar                       | None                                     |
       | LCHI  | botania                 | r1.10-363                | Botania+r1.10-363.jar                           | None                                     |
       | LCHI  | buildcraftbuilders      | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                    | None                                     |
       | LCHI  | buildcraftcompat        | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                    | None                                     |
       | LCHI  | buildcraftenergy        | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                    | None                                     |
       | LCHI  | buildcraftrobotics      | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                    | None                                     |
       | LCHI  | cctweaked               | 1.87.0                   | cc-tweaked-1.12.2-1.87.0.jar                    | None                                     |
       | LCHI  | computercraft           | 1.87.0                   | cc-tweaked-1.12.2-1.87.0.jar                    | None                                     |
       | LCHI  | chameleon               | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
       | LCHI  | codechickenlib          | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHI  | chickenchunks           | 2.4.2.74                 | ChickenChunks-1.12.2-2.4.2.74-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHI  | chisel                  | MC1.12.2-1.0.2.45        | Chisel-MC1.12.2-1.0.2.45.jar                    | None                                     |
       | LCHI  | redstoneflux            | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar         | None                                     |
       | LCHI  | cofhcore                | 4.6.6                    | CoFHCore-1.12.2-4.6.6.1-universal.jar           | None                                     |
       | LCHI  | cofhworld               | 1.4.0                    | CoFHWorld-1.12.2-1.4.0.1-universal.jar          | None                                     |
       | LCHI  | ic2                     | 2.8.197-ex112            | industrialcraft-2-2.8.197-ex112.jar             | de041f9f6187debbc77034a344134053277aa3b0 |
       | LCHI  | compactsolars           | 1.12.2-5.0.18.341        | CompactSolars-1.12.2-5.0.18.341-universal.jar   | None                                     |
       | LCHI  | mantle                  | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                        | None                                     |
       | LCHI  | twilightforest          | 3.10.1013                | twilightforest-1.12.2-3.10.1013-universal.jar   | None                                     |
       | LCHI  | tconstruct              | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                | None                                     |
       | LCHI  | conarm                  | 1.2.5.4                  | conarm-1.12.2-1.2.5.4.jar                       | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCHI  | customspawner           | 3.11.4                   | CustomMobSpawner-3.11.5.jar                     | None                                     |
       | LCHI  | customstartinggear      | 1.2.0                    | CustomStartingGear-1.12-1.2.0.9-universal.jar   | None                                     |
       | LCHI  | props                   | 2.6.3                    | Decocraft-2.6.3_1.12.2.jar                      | None                                     |
       | LCHI  | diethopper              | 1.1                      | diethopper-1.1.jar                              | None                                     |
       | LCHI  | dimdoors                | 3.0.9+287                | DimensionalDoors-3.0.9-287.jar                  | None                                     |
       | LCHI  | mocreatures             | 12.0.5                   | DrZharks+MoCreatures+Mod-12.0.5.jar             | None                                     |
       | LCHI  | dungeontactics          | DT-0.16.6                | DungeonTactics-1.12.2-0.16.6.jar                | None                                     |
       | LCHI  | eplus                   | 5.0.176                  | EnchantingPlus-1.12.2-5.0.176.jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHI  | enderstorage            | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHI  | energyconverters        | 1.3.6.24                 | energyconverters_1.12.2-1.3.6.24.jar            | None                                     |
       | LCHI  | waila                   | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
       | LCHI  | extracells              | 2.6.5                    | ExtraCells-1.12.2-2.6.5.jar                     | None                                     |
       | LCHI  | fairylights             | 2.1.10                   | fairylights-2.1.10-1.12.2.jar                   | None                                     |
       | LCHI  | forgelin                | 1.8.4                    | Forgelin-1.8.4.jar                              | None                                     |
       | LCHI  | forgemultipartcbe       | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHI  | microblockcbe           | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar    | None                                     |
       | LCHI  | minecraftmultipartcbe   | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar    | None                                     |
       | LCHI  | gardenstuff             | 1.12-2.1.1               | GardenStuff-1.12-2.1.1.jar                      | None                                     |
       | LCHI  | gravestone              | 1.10.2                   | gravestone-1.10.2.jar                           | None                                     |
       | LCHI  | gunpowderlib            | 1.12.2-1.0               | GunpowderLib-1.12.2-1.0.jar                     | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
       | LCHI  | helpfixer               | 1.12.1-1.5.18            | HelpFixer-1.12.1-1.5.18.jar                     | None                                     |
       | LCHI  | hopperducts             | 1.5                      | hopperducts-mc1.12-1.5.jar                      | None                                     |
       | LCHI  | teslacorelib            | 1.0.17                   | tesla-core-lib-1.12.2-1.0.17.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHI  | industrialforegoing     | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.12.13-237.jar      | None                                     |
       | LCHI  | natura                  | 1.12.2-4.3.2.69          | natura-1.12.2-4.3.2.69.jar                      | None                                     |
       | LCHI  | harvestcraft            | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zg.jar                 | None                                     |
       | LCHI  | thermalfoundation       | 2.6.7                    | ThermalFoundation-1.12.2-2.6.7.1-universal.jar  | None                                     |
       | LCHI  | integrationforegoing    | 1.12.2-1.10              | IntegrationForegoing-1.12.2-1.10.jar            | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
       | LCHI  | inventorytweaks         | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHI  | ironchest               | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                 | None                                     |
       | LCHI  | leverbuttonlights       | 1.12.2-3.4.0             | leverbuttonlights-1.12.2-3.4.0.jar              | None                                     |
       | LCHI  | thermalexpansion        | 5.5.7                    | ThermalExpansion-1.12.2-5.5.7.1-universal.jar   | None                                     |
       | LCHI  | logisticspipes          | 0.10.2.218               | logisticspipes-0.10.2.218.jar                   | e0c86912b2f7cc0cc646ad57799574aea43dbd45 |
       | LCHI  | millenaire              | Millénaire 8.0.1         | millenaire-8.0.1.jar                            | None                                     |
       | LCHI  | mrtjpcore               | 2.1.4.43                 | MrTJPCore-1.12.2-2.1.4.43-universal.jar         | None                                     |
       | LCHI  | nei                     | 2.4.3                    | NotEnoughItems-1.12.2-2.4.3.245-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHI  | pmp                     | 1.12.1                   | Plant-Mega-Pack-Mod-1.12.2.jar                  | None                                     |
       | LCHI  | pressure                | 1.3.1.9                  | Pressure-Pipes-Mod-1.12.2.jar                   | None                                     |
       | LCHI  | projectred-core         | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-Base.jar            | None                                     |
       | LCHI  | projectred-compat       | 1.0                      | ProjectRed-1.12.2-4.9.4.120-compat.jar          | None                                     |
       | LCHI  | projectred-integration  | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-integration.jar     | None                                     |
       | LCHI  | projectred-transmission | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-integration.jar     | None                                     |
       | LCHI  | projectred-fabrication  | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-fabrication.jar     | None                                     |
       | LCHI  | projectred-illumination | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-lighting.jar        | None                                     |
       | LCHI  | quickhomes              | 1.2.2                    | QuickHomes-1.2.2.jar                            | None                                     |
       | LCHI  | railcraft               | 12.0.0                   | railcraft-12.0.0.jar                            | a0c255ac501b2749537d5824bb0f0588bf0320fa |
       | LCHI  | reccomplex              | 1.4.8.2                  | RecurrentComplex-1.4.8.2.jar                    | None                                     |
       | LCHI  | redstonepaste           | 1.7.5                    | redstonepaste-mc1.12-1.7.5.jar                  | None                                     |
       | LCHI  | ruins                   | 17.2                     | Ruins-1.12.2.jar                                | None                                     |
       | LCHI  | storagedrawers          | 5.2.2                    | StorageDrawers-1.12.2-5.4.2.jar                 | None                                     |
       | LCHI  | storagedrawersextra     | @VERSION@                | StorageDrawersExtras-1.12-3.1.0.jar             | None                                     |
       | LCHI  | thermaldynamics         | 2.5.6                    | ThermalDynamics-1.12.2-2.5.6.1-universal.jar    | None                                     |
       | LCHI  | tinkersaddons           | 1.0.7                    | Tinkers'+Addons-1.12.1-1.0.7.jar                | None                                     |
       | LCHI  | tinkersjei              | 1.2                      | tinkersjei-1.2.jar                              | None                                     |
       | LCHI  | undergroundbiomes       | 1.3.8                    | UndergroundBiomesConstructs-1.12-1.3.8.jar      | None                                     |
       | LCHI  | unloader                | 1.2.0                    | unloader-1.2.0.jar                              | None                                     |
       | LCHI  | vanillafix              | 1.0.10-150               | VanillaFix-1.0.10-150.jar                       | None                                     |
       | LCHI  | veganlife               | 0.1.0                    | veganlife-1.12.2-1.5.0.jar                      | None                                     |
       | LCHI  | wanionlib               | 1.12.2-2.4               | WanionLib-1.12.2-2.4.jar                        | None                                     |
       | LCHI  | worldedit               | 6.1.10                   | worldedit-forge-mc1.12.2-6.1.10-dist.jar        | None                                     |
       | LCHI  | wrcbe                   | 2.3.2                    | WR-CBE-1.12.2-2.3.2.33-universal.jar            | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHI  | betteranimalsplus       | 9.0.1                    | betteranimalsplus-1.12.2-9.0.1.jar              | None                                     |
       | LCHI  | hungeroverhaul          | 1.12.2-1.3.3.jenkins148  | HungerOverhaul-1.12.2-1.3.3.jenkins148.jar      | None                                     |
       | LCHI  | mysticallib             | 1.12.2-1.7.0             | mysticallib-1.12.2-1.7.0.jar                    | None                                     |
       | LCHI  | teslacorelib_registries | 1.0.17                   | tesla-core-lib-1.12.2-1.0.17.jar                | None                                     |
       | LCHI  | unidict                 | 1.12.2-2.9.6             | UniDict-1.12.2-2.9.6.jar                        | None                                     |
  Loaded coremods (and transformers): LoadingPlugin (Xaeros_Minimap_20.11.0_Forge_1.12.jar)
                                        xaero.common.core.transformer.ChunkTransformer
                                        xaero.common.core.transformer.NetHandlerPlayClientTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      CorePlugin (SmoothFont-mc1.12.2-2.1.2.jar)
                                        bre.smoothfont.asm.Transformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
                                        
                                      LogisticsPipesCoreLoader (logisticspipes-0.10.2.218.jar)
                                        logisticspipes.asm.LogisticsClassTransformer
                                      NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
                                        net.fybertech.nwr.NWRTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
  AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
                                   - wailaIntegration (Enabled/Not Forced)
  Pulsar/natura loaded Pulses: - NaturaCommons (Enabled/Forced)
                               - NaturaOverworld (Enabled/Not Forced)
                               - NaturaNether (Enabled/Not Forced)
                               - NaturaDecorative (Enabled/Not Forced)
                               - NaturaTools (Enabled/Not Forced)
                               - NaturaEntities (Enabled/Not Forced)
                               - NaturaOredict (Enabled/Forced)
                               - NaturaWorld (Enabled/Not Forced)
  List of loaded APIs: * apAPI (3) from additionalpipes-6.0.0.8.jar
                       * AppleCoreAPI (3.2.0) from AppleCore-mc1.12.2-3.2.0.jar
                       * appliedenergistics2|API (rv6) from appliedenergistics2-rv6-stable-7.jar
                       * Baubles|API (1.4.0.2) from Baubles-1.12-1.5.2.jar
                       * BotaniaAPI (93) from Botania+r1.10-363.jar
                       * buildcraftapi_blocks (1.0) from buildcraft-all-7.99.24.6.jar
                       * buildcraftapi_boards (2.0) from buildcraft-all-7.99.24.6.jar
                       * buildcraftapi_core (2.2) from buildcraft-all-7.99.24.6.jar
                       * buildcraftapi_crops (1.1) from buildcraft-all-7.99.24.6.jar
                       * buildcraftapi_enums (1.0) from buildcraft-all-7.99.24.6.jar
                       * buildcraftapi_events (2.0) from buildcraft-all-7.99.24.6.jar
                       * buildcraftapi_facades (1.1) from buildcraft-all-7.99.24.6.jar
                       * buildcraftapi_filler (5.0) from buildcraft-all-7.99.24.6.jar
                       * buildcraftapi_fuels (2.0) from buildcraft-all-7.99.24.6.jar
                       * buildcraftapi_gates (4.1) from buildcraft-all-7.99.24.6.jar
                       * buildcraftapi_items (1.1) from buildcraft-all-7.99.24.6.jar
                       * buildcraftapi_library (2.0) from buildcraft-all-7.99.24.6.jar
                       * buildcraftapi_lists (1.0) from buildcraft-all-7.99.24.6.jar
                       * buildcraftapi_power (1.3) from buildcraft-all-7.99.24.6.jar
                       * buildcraftapi_recipes (3.0) from buildcraft-all-7.99.24.6.jar
                       * buildcraftapi_robotics (3.0) from buildcraft-all-7.99.24.6.jar
                       * buildcraftapi_statements (1.1) from buildcraft-all-7.99.24.6.jar
                       * buildcraftapi_tiles (1.2) from buildcraft-all-7.99.24.6.jar
                       * buildcraftapi_tools (1.0) from buildcraft-all-7.99.24.6.jar
                       * buildcraftapi_transport (5.0) from buildcraft-all-7.99.24.6.jar
                       * Chisel-API (0.0.1) from Chisel-MC1.12.2-1.0.2.45.jar
                       * ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-1.0.2.45.jar
                       * cofhapi (2.5.0) from CoFHCore-1.12.2-4.6.6.1-universal.jar
                       * ComputerCraft|API (1.87.0) from cc-tweaked-1.12.2-1.87.0.jar
                       * ComputerCraft|API|FileSystem (1.87.0) from cc-tweaked-1.12.2-1.87.0.jar
                       * ComputerCraft|API|Lua (1.87.0) from cc-tweaked-1.12.2-1.87.0.jar
                       * ComputerCraft|API|Media (1.87.0) from cc-tweaked-1.12.2-1.87.0.jar
                       * ComputerCraft|API|Network (1.87.0) from cc-tweaked-1.12.2-1.87.0.jar
                       * ComputerCraft|API|Network|Wired (1.87.0) from cc-tweaked-1.12.2-1.87.0.jar
                       * ComputerCraft|API|Peripheral (1.87.0) from cc-tweaked-1.12.2-1.87.0.jar
                       * ComputerCraft|API|Permissions (1.87.0) from cc-tweaked-1.12.2-1.87.0.jar
                       * ComputerCraft|API|Redstone (1.87.0) from cc-tweaked-1.12.2-1.87.0.jar
                       * ComputerCraft|API|Turtle (1.87.0) from cc-tweaked-1.12.2-1.87.0.jar
                       * ComputerCraft|API|Turtle|Event (1.87.0) from cc-tweaked-1.12.2-1.87.0.jar
                       * CSLib|API (1.0.1) from PTRLib-1.0.4.jar
                       * ctm-api (0.1.0) from CTM-MC1.12.2-1.0.2.31.jar
                       * ctm-api-events (0.1.0) from CTM-MC1.12.2-1.0.2.31.jar
                       * ctm-api-models (0.1.0) from CTM-MC1.12.2-1.0.2.31.jar
                       * ctm-api-textures (0.1.0) from CTM-MC1.12.2-1.0.2.31.jar
                       * ctm-api-utils (0.1.0) from CTM-MC1.12.2-1.0.2.31.jar
                       * industrialforegoingapi (5) from industrialforegoing-1.12.2-1.12.13-237.jar
                       * JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.15.0.291.jar
                       * pressureAPI (1.3.1.9) from Pressure-Pipes-Mod-1.12.2.jar
                       * projectred|api (2.1) from ProjectRed-1.12.2-4.9.4.120-Base.jar
                       * railcraft:api_carts (3.0.0) from railcraft-12.0.0.jar
                       * railcraft:api_charge (4.0.0) from railcraft-12.0.0.jar
                       * railcraft:api_core (3.2.0) from railcraft-12.0.0.jar
                       * railcraft:api_crafting (4.0.0) from railcraft-12.0.0.jar
                       * railcraft:api_events (2.0.0) from railcraft-12.0.0.jar
                       * railcraft:api_fuel (2.0.0) from railcraft-12.0.0.jar
                       * railcraft:api_helpers (2.0.0) from railcraft-12.0.0.jar
                       * railcraft:api_items (2.4.0) from railcraft-12.0.0.jar
                       * railcraft:api_signals (4.0.0) from railcraft-12.0.0.jar
                       * railcraft:api_tracks (5.1.1) from railcraft-12.0.0.jar
                       * redstonefluxapi (2.1.1) from RedstoneFlux-1.12-2.1.1.1-universal.jar
                       * StorageDrawersAPI (2.1.0) from StorageDrawers-1.12.2-5.4.2.jar
                       * StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12.2-5.4.2.jar
                       * StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12.2-5.4.2.jar
                       * StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12.2-5.4.2.jar
                       * StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12.2-5.4.2.jar
                       * StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12.2-5.4.2.jar
                       * Thaumcraft|API (6.0.2) from railcraft-12.0.0.jar
                       * WailaAPI (1.3) from Hwyla-1.8.26-B41_1.12.2.jar
  Suspected Mods: bspkrsCore (bspkrscore)
  Profiler Position: N/A (disabled)
  Is Modded: Definitely; Server brand changed to 'fml,forge'
  Type: Dedicated Server (map_server.txt)

**Comment by talesofmabria** [comment]
I also had this crash, and 7.6.0.1 also fixed it.  Unfortunately for anyone else, that version doesn't seem to exist to download anymore.

**Comment by winnipeg21** [comment]
Hey!

 Having the same or similar issues. Tried both the Universal and Deobf both resulted with the same error.
[Pastebin](https://pastebin.com/yPu017VT)

**Comment by Xcallono** [comment]
> I also had this crash, and 7.6.0.1 also fixed it. Unfortunately for anyone else, that version doesn't seem to exist to download anymore.

THANKFULLY for you, I ALSO run a server, and I happen to have a 7.6.0.1 copy leftover from my aging server! Here you go everyone!
https://www.mediafire.com/file/ngc2g2g76glq4sq/%255B1.12%255DbspkrsCore-universal-7.6.0.1.jar/file

**Comment by Nort432** [comment]
> > I also had this crash, and 7.6.0.1 also fixed it. Unfortunately for anyone else, that version doesn't seem to exist to download anymore.
> 
> THANKFULLY for you, I ALSO run a server, and I happen to have a 7.6.0.1 copy leftover from my aging server! Here you go everyone! https://www.mediafire.com/file/ngc2g2g76glq4sq/%255B1.12%255DbspkrsCore-universal-7.6.0.1.jar/file

It is works for me, thanks)

**Comment by Aquathing** [comment]
For anyone encountering this, you are probably using one of the "Updated" mods. So you need bspkrs updated https://www.curseforge.com/minecraft/mc-mods/bspkrscore-updated
