### ISSUE TITLE
Crash when trying to load Blood N Bones Classic

### ISSUE THREAD

**Issue by CHJ2000** [bspkrs/bspkrsCore#47]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 5/3/23 1:27 PM
Description: Initializing game

java.lang.ArrayIndexOutOfBoundsException: 0
	at bspkrs.util.ModVersionChecker.<init>(ModVersionChecker.java:62)
	at bspkrs.util.ModVersionChecker.<init>(ModVersionChecker.java:39)
	at bspkrs.util.ModVersionChecker.<init>(ModVersionChecker.java:119)
	at bspkrs.armorstatushud.fml.ArmorStatusHUDMod.preInit(ArmorStatusHUDMod.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:545)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:522)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:183)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:473)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
	at net.minecraft.client.main.Main.main(SourceFile:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at bspkrs.util.ModVersionChecker.<init>(ModVersionChecker.java:62)
	at bspkrs.util.ModVersionChecker.<init>(ModVersionChecker.java:39)
	at bspkrs.util.ModVersionChecker.<init>(ModVersionChecker.java:119)
	at bspkrs.armorstatushud.fml.ArmorStatusHUDMod.preInit(ArmorStatusHUDMod.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:545)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:522)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:183)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:473)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
	at net.minecraft.client.main.Main.main(SourceFile:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- System Details --
Details:
	Minecraft Version: 1.6.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1113037120 bytes (1061 MB) / 1780482048 bytes (1698 MB) up to 15837691904 bytes (15104 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx16992m -Xms256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Suspicious classes: FML and Forge are installed
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 150 mods loaded, 150 mods active
	mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{6.4.49.965} [Forge Mod Loader] (minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized
	Forge{9.11.1.965} [Minecraft Forge] (minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized
	AppliedEnergistics-Core{rv14.finale3} [AppliedEnergistics Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	CodeChickenCore{0.9.0.9} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	denLib{3.2.6} [denLib] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	Evoc{1.0.0} [Evoc] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	gasesCore{1.4.4.3} [Glenn's Gases Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	gasesFrameworkCore{1.0.3.1} [Gases Framework Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	MobiusCore{1.2.2} [MobiusCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	NotEnoughItems{1.6.1.9} [Not Enough Items] (notEnoughItems 1.6.1.9.jar) Unloaded->Constructed->Pre-initialized
	PowerCrystalsCore{1.1.8} [PowerCrystals Core] (PowerCrystalsCore-1.1.8-9.jar) Unloaded->Constructed->Pre-initialized
	TConstruct-Preloader{0.0.1} [Tinkers Corestruct] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	DenEvents{1.0} [DenEvents] (DenEvents.jar) Unloaded->Constructed->Pre-initialized
	bspkrsCore{v5.2(1.6.4)} [bspkrsCore] ([1.6.4]bspkrsCorev5.2.zip) Unloaded->Constructed->Pre-initialized
	ArmorStatusHUD{v1.15(1.6.4)} [ArmorStatusHUD] ([1.6.4]ArmorStatusHUDv1.15.zip) Unloaded->Constructed->Errored
	StatusEffectHUD{v1.19(1.6.4)} [StatusEffectHUD] ([1.6.4]StatusEffectHUDv1.19.zip) Unloaded->Constructed->Errored
	AppliedEnergistics{rv14.finale3} [Applied Energistics] (appeng-rv14-finale3-mc16x.jar) Unloaded->Constructed->Pre-initialized
	Backpack{1.28.37} [Backpack] (backpack-1.28.37-1.6.x.jar) Unloaded->Constructed->Pre-initialized
	ComputerCraft{1.63} [ComputerCraft] (computerCraft1.63.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded{1.6.4R2.7.9} [MineFactory Reloaded] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized
	CoFHCore{2.0.0.5} [CoFH Core] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized
	NetherOres{1.6.2R2.2.3} [Nether Ores] (NetherOres-2.2.3-final.jar) Unloaded->Constructed->Pre-initialized
	ForgeMultipart{1.0.0.250} [Forge Multipart] (ForgeMultipart-universal-1.6.4-1.0.0.250.jar) Unloaded->Constructed->Pre-initialized
	ThermalExpansion{3.0.0.7} [Thermal Expansion] (ThermalExpansion-3.0.0.7.jar) Unloaded->Constructed->Pre-initialized
	BigReactors{0.3.3A} [Big Reactors] (bigReactors-0.3.3A.jar) Unloaded->Constructed->Pre-initialized
	Natura{2.1.14} [Natura] (Natura_mc1.6.X_2.1.14.jar) Unloaded->Constructed->Pre-initialized
	BiomesOPlenty{1.2.1} [Biomes O' Plenty] (biomesOPlenty-universal-1.6.4-1.2.1.416.jar) Unloaded->Constructed->Pre-initialized
	AWWayofTime{v1.0.1g} [Blood Magic: Alchemical Wizardry] (Blood Magic v1.0.1g.zip) Unloaded->Constructed->Pre-initialized
	BnBTweaks{0.1.4} [Blood N' Bones Tweaks] (BnBTweaks-mc1.6.4-0.1.4.jar) Unloaded->Constructed->Pre-initialized
	Waila{1.5.2a} [Waila] (Waila_1.5.2a.zip) Unloaded->Constructed->Pre-initialized
	TConstruct{1.6.X_1.5.5.7} [Tinkers' Construct] (TConstruct_mc1.6.4_1.5.5.7.jar) Unloaded->Constructed->Pre-initialized
	DragonAPI{release} [DragonAPI] (DragonAPI 1.6 v25z.zip) Unloaded->Constructed->Pre-initialized
	CaveControl{beta} [CaveControl] (CaveControl 1.6 v25z.zip) Unloaded->Constructed->Pre-initialized
	ChickenChunks{1.3.3.4} [ChickenChunks] (chickenChunks 1.3.3.4.jar) Unloaded->Constructed->Pre-initialized
	CoFHLoot{2.0.0.5} [CoFH Loot] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized
	CoFHMasquerade{2.0.0.5} [CoFH Masquerade] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized
	CoFHSocial{2.0.0.5} [CoFH Social] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized
	CoFHWorld{2.0.0.5} [CoFH World] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized
	ConfigMod{v1.0} [Extended Mod Config] (configMod for MC v1.6.4.zip) Unloaded->Constructed->Pre-initialized
	CoroAI{v1.0} [CoroAI] (coroAI for MC v1.6.4.zip) Unloaded->Constructed->Pre-initialized
	CreeperCollateral{3.0.3} [CreeperCollateral] (creeperCollateral-1.6.4-3.0.3.jar) Unloaded->Constructed->Pre-initialized
	CustomChestLoot{1.1} [Custom Chest Loot] (customChestLoot 1.1 for MC 1.6.2.zip) Unloaded->Constructed->Pre-initialized
	DamageIndicatorsMod{2.9.2.4} [Damage Indicators] (damageIndicatorsv2.9.2.4.zip) Unloaded->Constructed->Pre-initialized
	DeadlyWorld{1.0.2} [Deadly World] (deadlyWorld 1.0.2 for MC 1.6.2.zip) Unloaded->Constructed->Pre-initialized
	DynamicLights{1.2.8} [Dynamic Lights] (dynamicLights_1.6.4.jar) Unloaded->Constructed->Pre-initialized
	DynamicLights_onFire{1.0.3} [Dynamic Lights on burning] (dynamicLights_1.6.4.jar) Unloaded->Constructed->Pre-initialized
	DynamicLights_creepers{1.0.3} [Dynamic Lights on Creepers] (dynamicLights_1.6.4.jar) Unloaded->Constructed->Pre-initialized
	DynamicLights_dropItems{1.0.5} [Dynamic Lights on ItemEntities] (dynamicLights_1.6.4.jar) Unloaded->Constructed->Pre-initialized
	DynamicLights_entityClasses{1.0.0} [Dynamic Lights on specified Entities] (dynamicLights_1.6.4.jar) Unloaded->Constructed->Pre-initialized
	DynamicLights_mobEquipment{1.0.3} [Dynamic Lights on Mob Equipment] (dynamicLights_1.6.4.jar) Unloaded->Constructed->Pre-initialized
	DynamicLights_flameArrows{1.0.0} [Dynamic Lights on Flame enchanted Arrows] (dynamicLights_1.6.4.jar) Unloaded->Constructed->Pre-initialized
	DynamicLights_otherPlayers{1.0.5} [Dynamic Lights Other Player Light] (dynamicLights_1.6.4.jar) Unloaded->Constructed->Pre-initialized
	DynamicLights_thePlayer{1.0.9} [Dynamic Lights Player Light] (dynamicLights_1.6.4.jar) Unloaded->Constructed->Pre-initialized
	dynamictanks{1.0} [Dynamic Liquid Tanks 2] (dynamicTanks2_v0.0.8a.jar) Unloaded->Constructed->Pre-initialized
	EnderForest{beta} [Ender Forest] (EnderForest 1.6 v25z.zip) Unloaded->Constructed->Pre-initialized
	EnhancedPortals3{1.6.4-3.0.0b5e} [EnhancedPortals] (enhancedPortals-1.6.4-3.0.0b5e.jar) Unloaded->Constructed->Pre-initialized
	ExtendedRenderer{v1.0} [Extended Renderer] (extendedRenderer for MC v1.6.4.zip) Unloaded->Constructed->Pre-initialized
	KeithyUtils{1.3} [Keithy Utils] (KeithyUtils-1.6.4-1.3.30.jar) Unloaded->Constructed->Pre-initialized
	Metallurgy3Core{3.4.0} [Metallurgy 3 Core] (Metallurgy-1.6.4-3.4.0.29.jar) Unloaded->Constructed->Pre-initialized
	Metallurgy3Vanilla{3.4.0} [Metallurgy 3 Vanilla] (Metallurgy-1.6.4-3.4.0.29.jar) Unloaded->Constructed->Pre-initialized
	Metallurgy3Base{3.4.0} [Metallurgy 3 Base] (Metallurgy-1.6.4-3.4.0.29.jar) Unloaded->Constructed->Pre-initialized
	ExtraTiC{0.8.4} [ExtraTiC] (ExtraTiC-1.6.4-0.8.4.jar) Unloaded->Constructed->Pre-initialized
	ExtraUtilities{1.0.3c} [Extra Utilities] (extrautils-1.0.3c.zip) Unloaded->Constructed->Pre-initialized
	flatsigns{1.4.0} [Flat Signs] (flatsigns-1.6.2-universal-1.4.0.15.jar) Unloaded->Constructed->Pre-initialized
	gasesFramework{1.0.3.1} [Gases Framework] (gasesFramework-1.0.3.1-1.6.4.jar) Unloaded->Constructed->Pre-initialized
	gases{1.4.4.3} [Glenn's Gases] (gases-1.4.4.3-1.6.4.jar) Unloaded->Constructed->Pre-initialized
	HardcoreEnderExpansion{1.6.1} [Hardcore Ender Expansion] (HardcoreEnderExpansion 1.6.1.zip) Unloaded->Constructed->Pre-initialized
	pamharvestcraft{1.0} [Pam's HarvestCraft Base] (pam's HarvestCraft 1.6.4 v1.1.4.zip) Unloaded->Constructed->Pre-initialized
	HungerOverhaul{1.6.X-2l} [Hunger Overhaul] (hungeroverhaul-1.6.X-2l-build3.zip) Unloaded->Constructed->Pre-initialized
	HarvestCraftWaila{1.0.4} [HarvestCraft Waila Fixes] (HarvestCraftWaila-mc1.6.4-1.0.4.jar) Unloaded->Constructed->Pre-initialized
	HostileWorlds{0.4} [Hostile Worlds] (hostile Worlds v0.4 Alpha Mod for MC v1.6.4.zip) Unloaded->Constructed->Pre-initialized
	IguanaTweaks{1.6.X-1i} [Iguana Tweaks] (iguanatweaks-1.6.X-1i-build4.zip) Unloaded->Constructed->Pre-initialized
	inventorytweaks{1.56} [Inventory Tweaks] (inventoryTweaks-MC1.6.2-1.56-b77.jar) Unloaded->Constructed->Pre-initialized
	JABBA{1.1.4} [JABBA] (JABBA_1.1.4.zip) Unloaded->Constructed->Pre-initialized
	LycanitesMobs{1.5.1h - MC 1.6.4} [Lycanites Mobs] (LycanitesMobsComplete 1.5.1h [1.6.4].jar) Unloaded->Constructed->Pre-initialized
	ArcticMobs{1.5.1h - MC 1.6.4} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.5.1h [1.6.4].jar) Unloaded->Constructed->Pre-initialized
	DemonMobs{1.5.1h - MC 1.6.4} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.5.1h [1.6.4].jar) Unloaded->Constructed->Pre-initialized
	DesertMobs{1.5.1h - MC 1.6.4} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.5.1h [1.6.4].jar) Unloaded->Constructed->Pre-initialized
	ForestMobs{1.5.1h - MC 1.6.4} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.5.1h [1.6.4].jar) Unloaded->Constructed->Pre-initialized
	InfernoMobs{1.5.1h - MC 1.6.4} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.5.1h [1.6.4].jar) Unloaded->Constructed->Pre-initialized
	JungleMobs{1.5.1h - MC 1.6.4} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.5.1h [1.6.4].jar) Unloaded->Constructed->Pre-initialized
	MountainMobs{1.5.1h - MC 1.6.4} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.5.1h [1.6.4].jar) Unloaded->Constructed->Pre-initialized
	PlainsMobs{1.5.1h - MC 1.6.4} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.5.1h [1.6.4].jar) Unloaded->Constructed->Pre-initialized
	SaltwaterMobs{1.5.1h - MC 1.6.4} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.5.1h [1.6.4].jar) Unloaded->Constructed->Pre-initialized
	SwampMobs{1.5.1h - MC 1.6.4} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.5.1h [1.6.4].jar) Unloaded->Constructed->Pre-initialized
	magicalcrops{3.2.1} [Magical Crops] (magical_crops_1.6.4_3.2.0_BETA_15a.zip) Unloaded->Constructed->Pre-initialized
	standardcrops{1.1.0} [Magical Crops - Crops & Food] (magical_crops_1.6.4_3.2.0_BETA_15a.zip) Unloaded->Constructed->Pre-initialized
	Metallurgy3Machines{3.4.0} [Metallurgy 3 Machines] (Metallurgy-1.6.4-3.4.0.29.jar) Unloaded->Constructed->Pre-initialized
	MFR Compat Forestry Trees{1.0} [MFR Compat Forestry Trees] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized
	MFR Compat Extra Trees{1.0} [MFR Compat Extra Trees] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatAppliedEnergistics{1.6.4R2.7.9} [MFR Compat: Applied Energistics] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatAtum{1.6.4R2.7.9} [MFR Compat: Atum] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatBackTools{1.6.4R2.7.9} [MFR Compat: BackTools] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatBuildCraft{1.6.4R2.7.9} [MFR Compat: BuildCraft] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatChococraft{1.6.4R2.7.9} [MFR Compat: Chococraft] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatExtraBiomes{1.6.4R2.7.9} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatForestry{1.6.4R2.7.9} [MFR Compat: Forestry] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatForestryPre{1.6.4R2.7.9} [MFR Compat: Forestry (part 2)] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatForgeMicroblock{1.6.4R2.7.9} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatIC2{1.6.4R2.7.9} [MFR Compat: IC2] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatMystcraft{1.6.4R2.7.9} [MFR Compat: Mystcraft] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatPams{1.6.4R2.7.9} [MFR Compat: Pam's Mods] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Core{4.3.5.30} [ProjectRed] (projectRedBase-1.6.4-4.3.5.30.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Exploration{4.3.5.30} [ProjectRed-Exploration] (projectRedWorld-1.6.4-4.3.5.30.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatProjRed{1.6.4R2.7.9} [MFR Compat ProjectRed] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatRailcraft{1.6.4R2.7.9} [MFR Compat: Railcraft] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatRP2{1.6.4R2.7.9} [MFR Compat: RP2] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatSufficientBiomes{1.6.4R2.7.9} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatThaumcraft{1.6.4R2.7.9} [MFR Compat: Thaumcraft] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatThermalExpansion{1.6.4R2.7.9} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatTwilightForest{1.6.4R2.7.9} [MFR Compat: TwilightForest] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatVanilla{1.6.4R2.7.9} [MFR Compat: Vanilla] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatXyCraft{1.6.4R2.7.9} [MFR Compat: XyCraft] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed->Pre-initialized
	BuildMod{v1.0} [Build Mod] (modBuild for MC v1.6.4.zip) Unloaded->Constructed->Pre-initialized
	MineTweaker{1.6.4-2.1.2} [MineTweaker] (zMineTweaker-1.6.4-2.3.1.jar) Unloaded->Constructed->Pre-initialized
	ModTweaker{0.3} [ModTweaker] (ModTweaker-1.6.4-0.3.jar) Unloaded->Constructed->Pre-initialized
	NaturalAbsorption{1.2} [Natural Absorption] (naturalAbsorption 1.2 for MC 1.6.4.zip) Unloaded->Constructed->Pre-initialized
	NEIAddons{1.10.4.64} [NEI Addons] (neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|AE{1.10.4.64} [NEI Addons: Applied Energistics] (neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|MiscPeripherals{1.10.4.64} [NEI Addons: Misc Peripherals] (neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|ExtraBees{1.10.4.64} [NEI Addons: Extra Bees] (neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|Forestry{1.10.4.64} [NEI Addons: Forestry] (neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|CraftingTables{1.10.4.64} [NEI Addons: Crafting Tables] (neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed->Pre-initialized
	NEIPlugins{1.1.0.6} [NEI Plugins] (neiplugins-1.1.0.6.jar) Unloaded->Constructed->Pre-initialized
	ObsidiPlates{2.0.0} [Obsidian Pressure Plates] (obsidiplates-1.6.2-universal-2.0.0.15.jar) Unloaded->Constructed->Pre-initialized
	Opis{1.2.2} [Opis] (Opis_1.2.2.zip) Unloaded->Constructed->Pre-initialized
	MapWriter{2.0.1} [MapWriter] (Opis_1.2.2.zip) Unloaded->Constructed->Pre-initialized
	ParticleMan{v1.0} [Particle Man] (particle Man v1.4 Mod for MC v1.6.4.zip) Unloaded->Constructed->Pre-initialized
	ProjRed|Transportation{4.3.5.30} [ProjectRed-Transportation] (projectRedMechanical-BETA-1.6.4-4.3.5.30.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Compatibility{4.3.5.30} [ProjectRed-Compatibility] (projectRedCompat-1.6.4-4.3.5.30.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Integration{4.3.5.30} [ProjectRed-Integration] (projectRedIntegration-1.6.4-4.3.5.30.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Transmission{4.3.5.30} [ProjectRed-Transmission] (projectRedIntegration-1.6.4-4.3.5.30.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Illumination{4.3.5.30} [ProjectRed-Illumination] (projectRedLighting-1.6.4-4.3.5.30.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Expansion{4.3.5.30} [ProjectRed-Expansion] (projectRedMechanical-BETA-1.6.4-4.3.5.30.jar) Unloaded->Constructed->Pre-initialized
	RandomThings{1.9} [Random Things] (Random_Things_v._1.9__MC_1.6.4_.jar) Unloaded->Constructed->Pre-initialized
	remoteIO{@MAJOR@.@MINOR@.@REVIS@.@BUILD@} [Remote IO] (remoteIO-universal-1.6.4-1.11.jar) Unloaded->Constructed->Pre-initialized
	Roguelike{1.3.3} [Roguelike Dungeons] (roguelike-v1.3.3-forge-1.6.4.zip) Unloaded->Constructed->Pre-initialized
	SpecialAI{1.0} [Special AI] (specialAI 1.0 PRE for MC 1.6.4.zip) Unloaded->Constructed->Pre-initialized
	SpecialMobs{3.0} [Special Mobs] (specialMobs 3.0 PRE for MC 1.6.2.zip) Unloaded->Constructed->Pre-initialized
	SpiceOfLife{1.1.1} [The Spice of Life] (SpiceOfLife-mc1.6.4-1.1.1.jar) Unloaded->Constructed->Pre-initialized
	TSteelworks{1.6.4-0.0.4.2-fix2} [Tinkers' Steelworks] (TSteelworks-mc1.6.4_0.0.4.2-fix2.jar) Unloaded->Constructed->Pre-initialized
	TiCTooltips{1.1.8a} [TiC Tooltips] (TiCTooltips-mc1.6.4-1.1.8a.jar) Unloaded->Constructed->Pre-initialized
	UtilityMobs{2.1} [Utility Mobs] (utilityMobs 2.1 for MC 1.6.2.zip) Unloaded->Constructed->Pre-initialized
	WailaHarvestability{1.1.0} [Waila Harvestability] (WailaHarvestability-mc1.6.4-1.1.0.jar) Unloaded->Constructed->Pre-initialized
	witchery{0.19.2} [Witchery] (witchery-1.6.4-0.19.2.zip) Unloaded->Constructed->Pre-initialized
	ZAMod{v1.9} [Zombie Awareness] (zombie Awareness v1.9 Mod for MC v1.6.4.zip) Unloaded->Constructed->Pre-initialized
	McMultipart{1.0.0.250} [Minecraft Multipart Plugin] (ForgeMultipart-universal-1.6.4-1.0.0.250.jar) Unloaded->Constructed->Pre-initialized
	IguanaTweaksTConstruct{1.6.X-1.0.3)} [TiC Tweaks] (tictweaks-1.6.4-1.0.3.jar) Unloaded->Constructed->Pre-initialized
	ForgeMicroblock{1.0.0.250} [Forge Microblocks] (ForgeMultipart-universal-1.6.4-1.0.0.250.jar) Unloaded->Constructed->Pre-initialized
	TConstruct Environment: Sane and ready for action. Bugs may be reported.
	Launched Version: forge-9.11.1.965
	LWJGL: 2.9.0
	OpenGL: Intel(R) Iris(R) Xe Graphics GL version 4.6.0 - Build 30.0.101.1298, Intel
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Pack: Default
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

**Comment by Kadah** [comment]
Disable the update check in the config.

**Comment by gtimbra** [comment]
> Disable the update check in the config.

Thank you! Was trying to get FTB Horizons (also using MC 1.6.4) working and this solved my issue :D

**Comment by major** [comment]
Always nice to see my name in an error message. 🤭

**Comment by minor** [comment]
Likewise (although not my name, just my handle)!
